FROM python:3.10-slim

WORKDIR /app

# instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && apt-get clean

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
